[input]
# Base for output and input.loss_curves.path
base_path = '../../'
# Building value per square metre for each category
asset_values = '../../asset_values.csv'

[input.impact]
# Where InaSAFE scenarios results are located
base_path = '../../inasafe/scenarios/'
## following are inasafe default ##
impact_map_name = 'impact_analysis.geojson'
# used to extract hazard category information
impact_styling_name = 'impact_analysis.qml'
# school, bank etc.
col_exposure_class = 'exposure_class'
# low, medium etc.
col_hazard_class = 'hazard_class'
col_hazard_id = 'hazard_id'
col_agg_name = 'aggregation_name'
# size in m2
col_size = 'size'
# boolean
col_affected = 'affected'

[input.loss_curves]
# Path to CSV loss curve. Relative to input.base_path
path = 'loss curves Budiyono2015/vulnerability_all.csv'
# column name
default = 'commercial'
# interpolation parameteters
max_value = 20.0
step = 0.01

[input.insurance]
# Return period to estimate the economic capital
rt_ec = 200
# Return on economic capital
rc = 0.02
margin = 0.2

[output]
# Relative to input.base_path
summary_file = "asset_losses.csv"
summary_map = "financial_summary.gpkg"

